spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/public_data_db
    username: hyun
    password: hyun123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace